project:
  type: website

website:
  title: Andrew Kates
  favicon: images/AK_logo1_transparent-crop.png
  navbar:
    title: false
    logo: images/AK_logo1_transparent-crop.png
    logo-alt: "Take me to the homepage"
    pinned: true
    right:
      - href: about.qmd
        text: About
      - posts.qmd # add your posts.qmd file to your navbar!
  page-footer: 
    left: "Copyright 2024, Andrew Kates"
    right: This website is built with [R](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
    
format:
  html:
    theme: styles.scss
    mainfont: Moderustic
    toc: true
    page-layout: full
    link-external-newwindow: true

editor: visual

execute: 
  freeze: auto



  

