project:
  type: website

website:
  title: Andrew Kates
  navbar:
    title: Andrew Kates
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd # add your posts.qmd file to your navbar!
  page-footer: 
    left: "Copyright 2024, Andrew Kates"
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto



  

